import 'dart:math';
import '../../../core/utils/japanese_utils.dart';
import '../../../models/cloze_word.dart';

/// ルールベースの自動穴埋め生成
class ClozeGenerator {
  final Random _random = Random();

  /// テキストから穴埋め対象語を自動生成
  /// [densityPercent]: 穴埋め密度 (5-30, デフォルト15)
  List<ClozeWord> generate(String text, {int densityPercent = 15}) {
    // 漢字語とカタカナ語を抽出
    final kanjiWords = JapaneseUtils.extractKanjiWords(text);
    final katakanaWords = JapaneseUtils.extractKatakanaWords(text);

    // 候補を統合
    final allCandidates = <WordPosition>[];
    allCandidates.addAll(kanjiWords);
    allCandidates.addAll(katakanaWords);

    // 助詞・助動詞・接続詞を除外
    allCandidates.removeWhere((wp) =>
        JapaneseUtils.isParticle(wp.word) ||
        JapaneseUtils.isAuxiliaryOrConjunction(wp.word));

    // 出現頻度を計算し、1〜3回の語を優先
    final frequencyMap = <String, int>{};
    for (final wp in allCandidates) {
      frequencyMap[wp.word] = (frequencyMap[wp.word] ?? 0) + 1;
    }

    // 重複除去（同じ開始位置の語は1つだけ）
    final seen = <int>{};
    final uniqueCandidates = <WordPosition>[];
    for (final wp in allCandidates) {
      if (!seen.contains(wp.startIndex)) {
        seen.add(wp.startIndex);
        uniqueCandidates.add(wp);
      }
    }

    // 出現頻度でソート（1〜3回の語を優先）
    uniqueCandidates.sort((a, b) {
      final freqA = frequencyMap[a.word] ?? 0;
      final freqB = frequencyMap[b.word] ?? 0;
      final priorityA = (freqA >= 1 && freqA <= 3) ? 0 : 1;
      final priorityB = (freqB >= 1 && freqB <= 3) ? 0 : 1;
      if (priorityA != priorityB) return priorityA.compareTo(priorityB);
      return a.startIndex.compareTo(b.startIndex);
    });

    // 密度に応じて選択数を決定
    final totalChars = text.length;
    final targetClozeChars = (totalChars * densityPercent / 100).round();
    int currentClozeChars = 0;

    // シャッフルしてランダムに選出
    final shuffled = List<WordPosition>.from(uniqueCandidates)..shuffle(_random);

    final selected = <ClozeWord>[];
    for (final wp in shuffled) {
      if (currentClozeChars >= targetClozeChars) break;
      // 重複チェック（既存の穴埋めと重ならないか）
      final overlaps = selected.any((cw) =>
          (wp.startIndex >= cw.startIndex && wp.startIndex < cw.endIndex) ||
          (wp.endIndex > cw.startIndex && wp.endIndex <= cw.endIndex));
      if (overlaps) continue;

      selected.add(ClozeWord(
        startIndex: wp.startIndex,
        endIndex: wp.endIndex,
        word: wp.word,
        isAutoGenerated: true,
      ));
      currentClozeChars += wp.word.length;
    }

    // 位置順にソート
    selected.sort((a, b) => a.startIndex.compareTo(b.startIndex));
    return selected;
  }

  /// Level に応じた穴埋め密度を返す
  static int densityForLevel(int level) {
    switch (level) {
      case 1:
        return 20;
      case 2:
        return 40;
      case 3:
        return 60;
      default:
        return 15;
    }
  }

  /// 選択肢（4択）を生成
  List<String> generateChoices(String correctAnswer, List<ClozeWord> allClozeWords) {
    final choices = <String>{correctAnswer};

    // 他の穴埋め語から選択肢を追加
    final otherWords = allClozeWords
        .where((cw) => cw.word != correctAnswer)
        .map((cw) => cw.word)
        .toList()
      ..shuffle(_random);

    for (final word in otherWords) {
      if (choices.length >= 4) break;
      choices.add(word);
    }

    // まだ足りない場合はダミー追加
    final dummyWords = ['対象', '規定', '条件', '手続', '権限', '義務', '責任', '制度'];
    for (final dummy in dummyWords..shuffle(_random)) {
      if (choices.length >= 4) break;
      if (!choices.contains(dummy)) {
        choices.add(dummy);
      }
    }

    final result = choices.toList()..shuffle(_random);
    return result;
  }
}
