// GENERATED CODE - DO NOT MODIFY BY HAND

part of 'cloze_word.dart';

// **************************************************************************
// TypeAdapterGenerator
// **************************************************************************

class ClozeWordAdapter extends TypeAdapter<ClozeWord> {
  @override
  final int typeId = 1;

  @override
  ClozeWord read(BinaryReader reader) {
    final numOfFields = reader.readByte();
    final fields = <int, dynamic>{
      for (int i = 0; i < numOfFields; i++) reader.readByte(): reader.read(),
    };
    return ClozeWord(
      startIndex: fields[0] as int,
      endIndex: fields[1] as int,
      word: fields[2] as String,
      isAutoGenerated: fields[3] as bool,
    );
  }

  @override
  void write(BinaryWriter writer, ClozeWord obj) {
    writer
      ..writeByte(4)
      ..writeByte(0)
      ..write(obj.startIndex)
      ..writeByte(1)
      ..write(obj.endIndex)
      ..writeByte(2)
      ..write(obj.word)
      ..writeByte(3)
      ..write(obj.isAutoGenerated);
  }

  @override
  int get hashCode => typeId.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ClozeWordAdapter &&
          runtimeType == other.runtimeType &&
          typeId == other.typeId;
}
