import 'package:hive/hive.dart';

part 'cloze_word.g.dart';

@HiveType(typeId: 1)
class ClozeWord {
  @HiveField(0)
  late int startIndex;

  @HiveField(1)
  late int endIndex;

  @HiveField(2)
  late String word;

  @HiveField(3)
  late bool isAutoGenerated;

  ClozeWord({
    required this.startIndex,
    required this.endIndex,
    required this.word,
    this.isAutoGenerated = true,
  });
}
