import 'dart:convert';
import 'dart:io';
import 'dart:typed_data';
import 'package:file_picker/file_picker.dart';
import 'package:hive/hive.dart';
import '../../models/script.dart';
import '../../models/practice_session.dart';
import '../../models/tts_dictionary_entry.dart';
import '../../models/allowed_pair.dart';
import '../../models/cloze_word.dart';

class BackupService {
  static Future<bool> exportBackup() async {
    try {
      final scriptsBox = Hive.box<Script>('scripts');
      final sessionsBox = Hive.box<PracticeSession>('practice_sessions');
      final ttsBox = Hive.box<TtsDictionaryEntry>('tts_dictionary');
      final allowedPairsBox = Hive.box<AllowedPair>('allowed_pairs');
      final settingsBox = Hive.box('app_settings');

      // 1. 各ボックスのデータをMap化
      final scriptsData = scriptsBox.values.map((s) => {
        'id': s.id,
        'title': s.title,
        'content': s.content,
        'category': s.category,
        'currentLevel': s.currentLevel,
        'practiceCount': s.practiceCount,
        'correctRate': s.correctRate,
        'bestVoiceScore': s.bestVoiceScore,
        'createdAt': s.createdAt.toIso8601String(),
        'lastPracticedAt': s.lastPracticedAt?.toIso8601String(),
        'clozeWords': s.clozeWords.map((cw) => {
          'startIndex': cw.startIndex,
          'endIndex': cw.endIndex,
          'word': cw.word,
          'isAutoGenerated': cw.isAutoGenerated,
        }).toList(),
        'tags': s.tags,
        'parenthesesMode': s.parenthesesMode,
        'fullTextHiragana': s.fullTextHiragana,
        'nextReviewAt': s.nextReviewAt?.toIso8601String(),
        'intervalDays': s.intervalDays,
        'easeFactor': s.easeFactor,
        'reviewPace': s.reviewPace,
        'targetDate': s.targetDate?.toIso8601String(),
        'generatedSchedule': s.generatedSchedule.map((d) => d.toIso8601String()).toList(),
        'scheduleIndex': s.scheduleIndex,
        'mistakeWords': s.mistakeWords,
        'pinnedClozeWords': s.pinnedClozeWords,
        'sortOrder': s.sortOrder,
        'rank': s.rank,
      }).toList();

      final sessionsData = sessionsBox.values.map((s) => {
        'id': s.id,
        'scriptId': s.scriptId,
        'mode': s.mode,
        'level': s.level,
        'score': s.score,
        'durationSeconds': s.durationSeconds,
        'recognizedText': s.recognizedText,
        'createdAt': s.createdAt.toIso8601String(),
      }).toList();

      final ttsData = ttsBox.values.map((e) => {
        'original': e.original,
        'reading': e.reading,
      }).toList();

      final allowedPairsData = allowedPairsBox.values.map((p) => {
        'id': p.id,
        'scriptId': p.scriptId,
        'originalWord': p.originalWord,
        'recognizedWord': p.recognizedWord,
        'originalHira': p.originalHira,
        'recognizedHira': p.recognizedHira,
        'createdAt': p.createdAt.toIso8601String(),
      }).toList();

      final settingsData = <String, dynamic>{};
      for (final key in settingsBox.keys) {
        settingsData[key.toString()] = settingsBox.get(key);
      }

      // 2. まとめてJSON文字列化
      final backupMap = {
        'version': 1,
        'exportedAt': DateTime.now().toIso8601String(),
        'scripts': scriptsData,
        'practice_sessions': sessionsData,
        'tts_dictionary': ttsData,
        'allowed_pairs': allowedPairsData,
        'app_settings': settingsData,
      };

      final jsonString = const JsonEncoder.withIndent('  ').convert(backupMap);
      final bytes = Uint8List.fromList(utf8.encode(jsonString));

      // 3. ファイルピッカーで保存
      final dateStr = DateTime.now().toString().substring(0, 10);
      final fileName = 'anripi_backup_$dateStr.json';

      final result = await FilePicker.platform.saveFile(
        dialogTitle: 'バックアップの保存先を選択してください',
        fileName: fileName,
        bytes: bytes,
      );

      return result != null;
    } catch (e) {
      // エラーは上位またはログでキャッチ可能にするため、実用上 print で留める
      return false;
    }
  }

  static Future<bool> importBackup() async {
    try {
      // 1. ファイルを選択して読込 (Googleドライブ等でのグレーアウトを避けるため FileType.any を使用)
      final result = await FilePicker.platform.pickFiles(
        type: FileType.any,
      );

      if (result == null) {
        return false;
      }

      final file = result.files.single;

      // 拡張子のチェック
      final extension = file.name.split('.').last.toLowerCase();
      if (extension != 'json') {
        throw Exception('JSONファイルを選択してください。');
      }

      Uint8List bytes;
      if (file.bytes != null) {
        bytes = file.bytes!;
      } else if (file.path != null) {
        // file.bytes が null の場合はローカルのパスから直接読み込む
        final ioFile = File(file.path!);
        bytes = await ioFile.readAsBytes();
      } else {
        throw Exception('ファイルを読み込めませんでした。');
      }

      final jsonString = utf8.decode(bytes);
      final Map<String, dynamic> backupMap = json.decode(jsonString);

      if (backupMap['version'] != 1) {
        throw Exception('不正なバックアップファイルのバージョンです。');
      }

      final scriptsBox = Hive.box<Script>('scripts');
      final sessionsBox = Hive.box<PracticeSession>('practice_sessions');
      final ttsBox = Hive.box<TtsDictionaryEntry>('tts_dictionary');
      final allowedPairsBox = Hive.box<AllowedPair>('allowed_pairs');
      final settingsBox = Hive.box('app_settings');

      // 2. ボックスのデータを一旦クリア
      await scriptsBox.clear();
      await sessionsBox.clear();
      await ttsBox.clear();
      await allowedPairsBox.clear();
      await settingsBox.clear();

      // 3. データの復元
      // app_settings
      final settingsData = backupMap['app_settings'] as Map<String, dynamic>? ?? {};
      for (final entry in settingsData.entries) {
        await settingsBox.put(entry.key, entry.value);
      }

      // scripts
      final scriptsList = backupMap['scripts'] as List? ?? [];
      for (final item in scriptsList) {
        final map = item as Map<String, dynamic>;
        final script = Script(
          id: map['id'],
          title: map['title'],
          content: map['content'],
          category: map['category'] ?? '',
          currentLevel: map['currentLevel'] ?? 0,
          practiceCount: map['practiceCount'] ?? 0,
          correctRate: (map['correctRate'] ?? 0.0) as double,
          bestVoiceScore: (map['bestVoiceScore'] ?? 0.0) as double,
          createdAt: DateTime.parse(map['createdAt']),
          lastPracticedAt: map['lastPracticedAt'] != null ? DateTime.parse(map['lastPracticedAt']) : null,
          clozeWords: (map['clozeWords'] as List?)?.map((item) => ClozeWord(
            startIndex: item['startIndex'],
            endIndex: item['endIndex'],
            word: item['word'],
            isAutoGenerated: item['isAutoGenerated'] ?? true,
          )).toList() ?? [],
          tags: List<String>.from(map['tags'] ?? []),
          parenthesesMode: map['parenthesesMode'] ?? 'stripContent',
          fullTextHiragana: map['fullTextHiragana'] ?? '',
          nextReviewAt: map['nextReviewAt'] != null ? DateTime.parse(map['nextReviewAt']) : null,
          intervalDays: (map['intervalDays'] ?? 0.0) as double,
          easeFactor: (map['easeFactor'] ?? 2.5) as double,
          reviewPace: map['reviewPace'] ?? 'normal',
          targetDate: map['targetDate'] != null ? DateTime.parse(map['targetDate']) : null,
          generatedSchedule: (map['generatedSchedule'] as List?)?.map((d) => DateTime.parse(d)).toList() ?? [],
          scheduleIndex: map['scheduleIndex'] ?? 0,
          mistakeWords: map['mistakeWords'] != null ? Map<String, int>.from(map['mistakeWords']) : {},
          pinnedClozeWords: List<String>.from(map['pinnedClozeWords'] ?? []),
          sortOrder: map['sortOrder'] ?? 0,
          rank: map['rank'] ?? 'B',
        );
        await scriptsBox.put(script.id, script);
      }

      // practice_sessions
      final sessionsList = backupMap['practice_sessions'] as List? ?? [];
      for (final item in sessionsList) {
        final map = item as Map<String, dynamic>;
        final session = PracticeSession(
          id: map['id'],
          scriptId: map['scriptId'],
          mode: map['mode'],
          level: map['level'],
          score: (map['score'] ?? 0.0) as double,
          durationSeconds: map['durationSeconds'] ?? 0,
          recognizedText: map['recognizedText'],
          createdAt: DateTime.parse(map['createdAt']),
        );
        await sessionsBox.put(session.id, session);
      }

      // tts_dictionary
      final ttsList = backupMap['tts_dictionary'] as List? ?? [];
      for (final item in ttsList) {
        final map = item as Map<String, dynamic>;
        final entry = TtsDictionaryEntry(
          original: map['original'],
          reading: map['reading'],
        );
        await ttsBox.put(entry.original, entry);
      }

      // allowed_pairs
      final allowedPairsList = backupMap['allowed_pairs'] as List? ?? [];
      for (final item in allowedPairsList) {
        final map = item as Map<String, dynamic>;
        final pair = AllowedPair(
          id: map['id'],
          scriptId: map['scriptId'],
          originalWord: map['originalWord'],
          recognizedWord: map['recognizedWord'],
          originalHira: map['originalHira'],
          recognizedHira: map['recognizedHira'],
          createdAt: DateTime.parse(map['createdAt']),
        );
        await allowedPairsBox.put(pair.id, pair);
      }

      return true;
    } catch (e) {
      return false;
    }
  }
}
